### ISSUE TITLE
[Epic] parity with balancer managed pool interface

### ISSUE THREAD

**Issue by MickdeGraaf** [pie-dao/pie-smart-pools#25]
#### User Story

- As an <audience/user>: Balancer
- I want to <action/task>: Know that the PieDAO interface is the same as my managed pools
- so that <outcome/goal/benefit>: So I don't have to write any custom code to make them work

#### Type

- [x] Enhancement
- [ ] Maintenance
- [ ] Refactor

#### Description

Balancer is improving their smart order router and user interfaces to work better with managed pools. Implementing a common interface would allow us to better integrate with the Balancer ecosystem.

Interface we want to implement: https://github.com/balancer-labs/smart-pools/blob/master/crp/contracts/ConfigurableRightsPool.sol

#### Definition of Done

- [x] `getDenormalizedWeight(address token)`
- [ ] `function finalizeSmartPool()`
- [ ] `function createPool()`
- [x] `function updateWeight(address token, uint256 newWeight)`
- [x] `function updateWeightsGradually(uint256[] calldata newWeights, uint256 startBlock, uint256 endBlock)`
- [x] `function pokeWeights()`
- [x] `function commitAddToken(address token, uint balance, uint denormalizedWeight)`
- [x] `function applyAddToken()`
- [x] `function removeToken(address token)`
- [x] `function joinswapExternAmountIn(address tokenIn, uint256 tokenAmountIn)`
- [x] `function joinswapPoolAmountOut(uint poolAmountOut, address tokenIn)`
- [x] `function exitswapPoolAmountIn(uint poolAmountIn, address tokenOut)`
- [x] `function exitswapExternAmountOut(address tokenOut, uint tokenAmountOut)`
- [x] Test coverage for all the functionality above

**Comment by MickdeGraaf** [comment]
Implemented in #51
