### ISSUE TITLE
[Epic] V2 Smart Pool fixes

### ISSUE THREAD

**Issue by MickdeGraaf** [pie-dao/pie-smart-pools#57]
## Description

Some issues have surfaced in our v2 version of the smart pools. This epic will give us a single source to track pending fixes in sepperate issues.

## Initiative / goal

Get the V2 smart pools production ready

## Acceptance criteria and must have scope

- [x] Lock underlying balancer pool during entry and exit #58
- [x] Do not update weight of token in `pokeWeights` when startWeight[i] == newWeights[i] 
- [x] Stop weight adjustment when binding, unbinding, rebinding or changing the weights of the pool 
- [x] Set `startBlock` to zero after pokeWeights finished adjusting weights to prevent old weights being applied #59 

## Stakeholders

@MickdeGraaf 

## Timeline

05/09-06/09 (European notation)

**Comment by MickdeGraaf** [comment]
We can also consider disallow adding and removal of tokens during a rebalance.
This would greatly simplify the implementation but would make the pools less versatile.
